services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    restart: "on-failure"

#  kafka-1:
#    image: confluentinc/cp-kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - 9092:9092
#    restart: "on-failure"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  kafka-2:
#    image: confluentinc/cp-kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - 9093:9093
#    restart: "on-failure"
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-3:
    image: confluentinc/cp-server:5.4.0
    container_name: broker-test
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    restart: "on-failure"
    environment:
      KAFKA_BROKER_ID : 2
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://broker-test:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_METRIC_REPORTERS : io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR : 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS : 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR : 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS : broker-test:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT : zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS : 1
      CONFLUENT_METRICS_ENABLE : true
      CONFLUENT_SUPPORT_CUSTOMER_ID : anonymous
