
spring:
  application:
    name: notification-service
  profiles:
    active: default
  kafka:
    producer:
      bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
      value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key.serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: manual
server:
  port: 8080
  servlet:
    context-path: /account-service
